'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';

const writerNames = {gannon: 'Maude Gannon', crane: 'Hollis Crane', sorrell: 'Conrad Sorrell', kells: 'Marnie Kells', march: 'Sabine March', pike: 'Dashiell Pike'};
const emptyArticle = {slug: '', title: '', dek: '', body_text: '', writer_slug: 'gannon', section: 'The League', status: 'draft'};
const emptyMemory = {subject_type: 'league', subject_key: '', memory_key: '', content: '', status: 'active'};

export default function ManagementConsole({tenant, owner, articles, memories, access}) {
  const router = useRouter();
  const [tab, setTab] = useState('articles');
  const [status, setStatus] = useState('');
  const [busy, setBusy] = useState(false);
  const [article, setArticle] = useState(null);
  const [memory, setMemory] = useState(null);
  const canAdmin = ['admin', 'owner'].includes(tenant.role);
  async function save(action, fields) {
    if (busy) return false;
    setBusy(true); setStatus('Saving…');
    try {
      const response = await fetch('/api/manage', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({...fields, action, tenant: tenant.slug})});
      const result = await response.json();
      if (!response.ok) {setStatus(result.error || 'Could not save.'); return false;}
      setStatus(action === 'grantAccess' ? 'Access granted. Share the management link below with them.' : action === 'revokeAccess' ? 'Access revoked.' : 'Saved.');
      router.refresh(); return true;
    } catch {setStatus('The management service could not be reached.'); return false;}
    finally {setBusy(false);}
  }
  const tabs = [['articles', 'Articles'], ['memory', 'Newsroom context'], ...(canAdmin ? [['settings', 'Settings']] : []), ...(owner ? [['members', 'Members']] : [])];
  return <section>
    <nav className="managementTabs" aria-label="Bureau management">{tabs.map(([key, label]) => <button key={key} type="button" onClick={() => {setTab(key); setStatus('');}} className={tab === key ? 'selected' : ''} aria-current={tab === key ? 'page' : undefined}>{label}</button>)}</nav>
    <p role="status" className="managementStatus">{status}</p>
    {tab === 'articles' && <div>
      <div className="managementSectionHead"><div><h2>Local stories</h2><p>Articles published here appear only in {tenant.name}.</p></div><button onClick={() => setArticle({...emptyArticle})}>New article</button></div>
      {!articles.length && !article && <div className="managementEmpty"><h3>The desk is clear.</h3><p>Write the first local story for this bureau.</p></div>}
      <div className="managementList">{articles.map(item => <div className="managementRow" key={item.id}><div><span className="managementBadge">{item.status}</span><h3>{item.title}</h3><p>{writerNames[item.writer_slug]} · {item.section}</p>{item.status === 'published' && tenant.slug === 'sunday-crew' && <Link href={`/sunday-crew/articles/${item.slug}`}>View published story ↗</Link>}</div><button className="managementSecondary" onClick={() => setArticle({...item, body_text: (Array.isArray(item.body) ? item.body : []).filter(p => typeof p === 'string').join('\n\n')})}>Edit</button></div>)}</div>
      {article && <form className="managementForm" onSubmit={async event => {event.preventDefault(); if (await save('saveArticle', article)) setArticle(null);}}><h3>{article.id ? 'Edit article' : 'New article'}</h3><div className="managementFieldGrid"><label>Headline<input value={article.title} required maxLength={240} onChange={e => setArticle({...article, title: e.target.value})}/></label><label>URL slug<input value={article.slug} required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={100} onChange={e => setArticle({...article, slug: e.target.value})}/></label></div><label>Subtitle<textarea value={article.dek} maxLength={800} rows={2} onChange={e => setArticle({...article, dek: e.target.value})}/></label><div className="managementFieldGrid"><label>Correspondent<select value={article.writer_slug} onChange={e => setArticle({...article, writer_slug: e.target.value})}>{Object.entries(writerNames).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label><label>Section<input value={article.section} maxLength={80} required onChange={e => setArticle({...article, section: e.target.value})}/></label></div><label>Story<textarea value={article.body_text} rows={12} maxLength={50000} required onChange={e => setArticle({...article, body_text: e.target.value})}/><small>Separate paragraphs with a blank line.</small></label><label>Status<select value={article.status} onChange={e => setArticle({...article, status: e.target.value})}><option value="draft">Draft</option><option value="review">Ready for review</option><option value="published">Published</option><option value="archived">Archived</option></select></label><div className="managementActions"><button disabled={busy}>{busy ? 'Saving…' : article.status === 'published' ? 'Save and publish' : 'Save article'}</button><button type="button" className="managementSecondary" disabled={busy} onClick={() => setArticle(null)}>Cancel</button></div></form>}
    </div>}
    {tab === 'memory' && <div><div className="managementSectionHead"><div><h2>Teach the room.</h2><p>League history, rivalries, running jokes, and the people our correspondents know here.</p></div><button onClick={() => setMemory({...emptyMemory})}>Add context</button></div><div className="managementList">{memories.map(item => <div className="managementRow" key={item.id}><div><span className="managementBadge">{item.subject_type} · {item.status}</span><h3>{item.memory_key.replaceAll('_', ' ')}</h3><p className="managementMemory">{item.content}</p></div><button className="managementSecondary" onClick={() => setMemory({...item})}>Edit</button></div>)}</div>{!memories.length && !memory && <div className="managementEmpty"><h3>A clean slate.</h3><p>Add the local context that makes this league its own.</p></div>}{memory && <form className="managementForm" onSubmit={async event => {event.preventDefault(); if (await save('saveMemory', memory)) setMemory(null);}}><h3>{memory.id ? 'Edit context' : 'Add context'}</h3><div className="managementFieldGrid"><label>Type<select value={memory.subject_type} onChange={e => setMemory({...memory, subject_type: e.target.value})}>{['league', 'manager', 'team', 'rivalry', 'joke', 'event', 'preference', 'correspondent'].map(type => <option key={type}>{type}</option>)}</select></label><label>Person, team, or correspondent key<input value={memory.subject_key || ''} maxLength={100} onChange={e => setMemory({...memory, subject_key: e.target.value})}/><small>Correspondents: gannon, crane, sorrell, kells, march, pike.</small></label></div><label>Label<input value={memory.memory_key} maxLength={120} required onChange={e => setMemory({...memory, memory_key: e.target.value})}/></label><label>Context<textarea value={memory.content} rows={6} maxLength={10000} required onChange={e => setMemory({...memory, content: e.target.value})}/></label><label>Status<select value={memory.status} onChange={e => setMemory({...memory, status: e.target.value})}>{['active', 'retired', 'disputed'].map(value => <option key={value}>{value}</option>)}</select></label><div className="managementActions"><button disabled={busy}>Save context</button><button type="button" className="managementSecondary" disabled={busy} onClick={() => setMemory(null)}>Cancel</button></div></form>}</div>}
    {tab === 'settings' && canAdmin && <form className="managementForm" onSubmit={event => {event.preventDefault(); save('saveSettings', Object.fromEntries(new FormData(event.currentTarget)));}}><h2>Publication settings</h2><p>Update this bureau’s publication name.</p><label>Publication name<input name="publication_name" defaultValue={tenant.publication_name} maxLength={120} required/></label><button disabled={busy}>Save settings</button></form>}
    {tab === 'members' && owner && <div><div className="managementSectionHead"><div><h2>Give someone a desk.</h2><p>Access applies only to {tenant.name}. You retain owner control.</p></div></div><form className="managementForm" onSubmit={async event => {event.preventDefault(); const form = event.currentTarget; if (await save('grantAccess', Object.fromEntries(new FormData(form)))) form.reset();}}><div className="managementFieldGrid"><label>Email address<input name="email" type="email" autoComplete="off" required maxLength={254}/></label><label>Role<select name="role"><option value="admin">Admin — content and publication settings</option><option value="editor">Editor — articles and newsroom context</option></select></label></div><button disabled={busy}>Grant access</button><p className="managementNote">After granting access, share <b>{typeof window === 'undefined' ? 'ordinarybrief.com/manage' : `${window.location.origin}/manage`}</b>. They sign in with the assigned email. This proof of concept does not send invitation emails.</p></form><div className="managementList">{access.map(member => <div className="managementRow" key={member.id}><div><h3>{member.email}</h3><span className="managementBadge">{member.role}</span></div><button disabled={busy} className="managementSecondary" onClick={() => save('revokeAccess', {id: member.id})}>Revoke access</button></div>)}</div>{!access.length && <p>No other managers assigned.</p>}</div>}
  </section>;
}
