import {writers} from '../articles/writers';
const findings=[
 {writer:'gannon',label:'The margin',title:'Route 22 scored 167.94. The season has found a smaller decimal to argue about.',body:'Kraft won 168.22–167.94, turning the week’s two highest scores into one very expensive loss. Route 22 already lost by 0.56 in Week 2; this one cost half as much. The Clubhouse is 2–2, and its two defeats total 0.84 points. That is a real scheduling grievance. It is also why we should resist treating every loss as a referendum on roster construction.',receipt:'0.28 • THIS WEEK / 0.84 • TWO LOSSES'},
 {writer:'pike',label:'The unused asset',title:'Danir owned the breakout. Ownership was not the difficult part.',body:'Kyle Monangai scored 35 on the bench while Dontayvion Wicks supplied 3.8 from a FLEX spot. Kupp won by 18.20. The 31.2-point gap would have changed the result, although the result alone cannot tell us what was knowable before kickoff. Danir falls to 1–3; the next useful question is how a player earns his way into this lineup.',receipt:'143.62–125.42 • KUPP MOVES TO 3–1'},
 {writer:'crane',label:'The contradictory documents',title:'Pollard Greens leads the league in points. Hopkins has the first-place record.',body:'Hopkins survived 155.70–153.16 and returned to the top of the table at 3–1. Pollard is 2–2 despite a league-high 610.07 points. A 2.54-point margin is not much evidence of a meaningful difference between the teams. It is, however, exactly enough evidence for the standings.',receipt:'610.07 PF • FIRST IN SCORING, FIFTH IN THE TABLE'},
 {writer:'march',label:'The perfect record',title:'Lloyd’s undefeated season ended with a perfectly good decision in the lineup.',body:'Emanuel Wilson supplied 30.6 from a FLEX spot. CeeDeep still won 147.07–141.28, leaving both teams at 3–1. The Katz family office did not need to have done something foolish for its perfect record to end. Sometimes the other side simply arrives with 5.79 more points, and the retrospective should have the manners to admit it.',receipt:'CEEDEEP 3–1 / LLOYD 3–1'},
 {writer:'sorrell',label:'The next hearing',title:'All Ugly is still waiting for the standings to recognize its position.',body:'Skatt won 149.47–132.98 behind 39.8 from Kyren Williams and reached 2–2. All Ugly is 0–4. There have been losses worth explaining in detail; this one was 16.49 points wide. The first win remains the most useful piece of evidence the organization has yet to produce.',receipt:'SKATT: 2–2 • ALL UGLY: 0–4'},
 {writer:'kells',label:'The closing argument',title:'Royrek and Shake ’N Baker have separated by one win and several opinions.',body:'Royrek won 133.88–130.24 and reached 2–2; Shake falls to 1–3. A 3.64-point margin is just large enough to be recorded without an asterisk and small enough to support a week of alternate endings. Unfortunately, the league accepts only the one that happened.',receipt:'3.64 POINTS • ONE OFFICIAL ENDING'}
];
function Finding({f}){const w=writers[f.writer];return <><div className="autopsyByline"><img loading="lazy" decoding="async" src={w.image} alt={w.imageAlt}/><span><small>{w.name.toUpperCase()} • {w.title.toUpperCase()}</small><b>{f.label}</b></span></div><h3>{f.title}</h3><p>{f.body}</p><strong>{f.receipt}</strong></>}
export default function LoogAutopsy(){return <section className="section autopsySection" id="league"><div className="autopsyHeader"><div><small>THE NEWSROOM • WEEK 4 POSTMORTEM</small><h2>Week 4 Autopsy</h2></div><span>FINAL SCORES / FOUR WEEKS OF RECEIPTS</span></div><div className="autopsyLead"><Finding f={findings[0]}/></div><div className="autopsyNewsroom">{findings.slice(1).map(f=><article key={f.writer}><Finding f={f}/></article>)}</div></section>}
