import {writers} from '../articles/writers';
const findings=[
  {writer:'march',label:'The breakthrough',title:'Tet McMillan finally gave CHANE GANG something other than a case for sympathy.',body:'Two weeks ago, Cody lost by 0.32. This time Tet McMillan supplied 45.2 points and CHANE GANG beat Rhamondre — A Cautionary Tale by eight for its first win. The useful story is the breakout: one receiver accounted for more than a third of the winning score and changed the afternoon. At 1–3, there is still repair work ahead. For once, the Monday conversation can begin with a player who delivered instead of a decimal that did not.',receipt:'117.38–109.38 • FIRST WIN • TET: 45.2'},
  {writer:'crane',label:'The evidence locker',title:'There were two unbeaten teams. Tolbert’s Cookies has retained the stationery.',body:'Greg’s team beat Wake Me Up On September 1st, 129.08–104.98, and left with the league’s only 4–0 record. Kyren Williams and Javonte Williams supplied 60.5 points between them. Nipun’s three-week winning streak ends here; the undefeated stationery now belongs to a business named after cookies. I checked the arithmetic. It is legally theirs.',receipt:'4–0 • THE LAST PERFECT RECORD'},
  {writer:'gannon',label:'The football finding',title:'ALLENtown’s third straight win was not especially interested in being close.',body:'Ravi followed wins over ZAYWATCH and CHANE GANG with a 168.26–115.22 dismissal of A Stroke of Bad Luck. CeeDee Lamb’s 39.8 points led the week’s highest-scoring lineup. Across the field, Kenneth Walker’s 37.4 was real production with nowhere useful to go. Andrew has now lost three straight since opening with 184.72. A strong individual performance is evidence; it is not a complete team.',receipt:'53.04-POINT MARGIN • THREE STRAIGHT FOR ALLENTOWN'},
  {writer:'pike',label:'The balance sheet',title:'Scrump leads the league in points and occupies eighth place. Both numbers are correct.',body:'Last week Scrump scored 191.28. This week it scored 114.52 and lost to J Bird, whose first win arrived at the fourth attempt. Scrump’s 540.36 season points still lead Sunday Crew, but a 1–3 record has a less impressive view from the table. Weekly scoring is not transferable: the surplus from one Sunday cannot be carried into the next. Fantasy football remains a remarkably hostile savings account.',receipt:'540.36 PF • LEAGUE HIGH • 1–3'},
  {writer:'sorrell',label:'The name under examination',title:'RBs are Overrated continues to accept substantial donations from running backs.',body:'Chuba Hubbard scored 27.4 and Tony Pollard added 12 as Runit beat Croatian Sensation, 157.82–123.06. The franchise moves to 3–1 while maintaining a name that its own payroll keeps disputing. Paul falls to 2–2 despite 28.2 from Tee Higgins and 27.16 from Drake Maye. Some weeks the headline performances are perfectly adequate. The opponent is simply having a better one.',receipt:'157.82–123.06 • RBs ARE OVERRATED: 3–1'},
  {writer:'kells',label:'The recovery arc',title:'ZAYWATCH has gone from 0–2 to an entirely different tone of voice.',body:'Sandy followed last week’s win over Rhamondre with a 128.98–112.44 win over Forte inch Ditka. Emanuel Wilson supplied 25.5; ZAYWATCH is back at 2–2. Matt has travelled the same distance in the opposite direction, following a 2–0 start with two losses. Both arrive at .500, where one franchise calls it momentum and the other would prefer we stop asking.',receipt:'TWO STRAIGHT WINS / TWO STRAIGHT LOSSES / SAME RECORD'}
];
function Byline({finding}){const w=writers[finding.writer];return <div className="autopsyByline"><img loading="lazy" decoding="async" src={w.image} alt={w.imageAlt}/><span><small>{w.name.toUpperCase()} • {w.title.toUpperCase()}</small><b>{finding.label}</b></span></div>}
export default function SundayCrewAutopsy(){const [lead,...rest]=findings;return <section className="section autopsySection" id="league"><div className="autopsyHeader"><div><small>THE NEWSROOM • SUNDAY CREW • WEEK 4 POSTMORTEM</small><h2>Week 4 Autopsy</h2></div><span>FOUR WEEKS OF RECEIPTS / SIX LOCAL FINDINGS</span></div><div className="autopsyLead"><Byline finding={lead}/><h3>{lead.title}</h3><p>{lead.body}</p><strong>{lead.receipt}</strong></div><div className="autopsyNewsroom">{rest.map(f=><article key={f.writer}><Byline finding={f}/><h3>{f.title}</h3><p>{f.body}</p><strong>{f.receipt}</strong></article>)}</div></section>}
