export const teams=[
{id:'all-ugly',team:'The All Ugly Team',owners:'Cody + Ferret',aliases:'Co-managers',record:'0-1',pf:'152.86',note:'Scored 152.86, lost anyway, and immediately discovered that Expected Wins is a beautiful and important statistic.',lore:'Caleb Williams dropped 39.26 and Christian Watson 36.7. Management would like the record to reflect that this was a very sophisticated loss.'},
{id:'hopkins-opus',team:'Mr Hopkins Opus',owners:'Matt Kushner',aliases:'Kash • Kush',record:'1-0',pf:'181.60',note:'The league-high 181.60 has given Kash exactly the amount of evidence nobody wanted him to possess.',lore:'Kenneth Walker scored 44.4. Jaxson Dart scored 28.7. Every group-chat argument involving Kash is now in immediate danger of becoming a Week 1 retrospective.'},
{id:'lloyd-rings',team:'Lloyd of the Rings',owners:'Jordan Katz + Brandon Katz',aliases:'The Katz Brothers',record:'1-0',pf:'166.30',note:'Henry and Flowers combined for 73.7 while the rest of us were apparently playing a different sport.',lore:'A co-managed family enterprise that scored 166.30 despite getting four points from the player literally named Lloyd. Annoyingly competent.'},
{id:'royrek',team:'Royrek Tishmeshulum',owners:'Max Levene',aliases:'Bonanz • Bonez',record:'1-0',pf:'160.91',note:'Jefferson, Lamar and Goedert carried Bonanz to 160.91 and ruined an otherwise excellent All Ugly week.',lore:'The franchise’s central constitutional question remains unchanged: where does Bonanz end and alleged shadow GM Bartone begin?'},
{id:'kraft',team:'For the Love of the Kraft',owners:'Derek Tishman',aliases:'Tony Tish • Tish',record:'1-0',pf:'148.16',note:'D’Andre Swift scored 38.2, which is one way to avoid having to explain much else.',lore:'Tish opened 1-0, then immediately added Antonio Williams. Competence is being investigated as a possible clerical error.'},
{id:'route-22',team:'The Route 22 Clubhouse',owners:'Danny Choe + Max Gersten',aliases:'Che • Gerstone',record:'1-0',pf:'147.90',note:'Won while starting Matthew Stafford for 3.3 points. This has only encouraged them.',lore:'Jeanty scored 39, Pittsburgh D/ST scored 22, and the Clubhouse responded to victory by attempting to acquire every other asset in North America.'},
{id:'kupp-doubs',team:'Kupp Kupp Doubs',owners:'Roy',aliases:'Roy Bird',record:'1-0',pf:'143.16',note:'Won 143.16–130.72 while a completely unnecessary 37.8 points from Jalen Coker sat on the bench.',lore:'Roy Bird escaped Week 1 with both a win and an unopened emergency supply of points. Extremely irritating asset management.'},
{id:'pollard-greens',team:'Pollard Greens',owners:'Marc Sherman',aliases:'Sherm • Sherm the Worm • Big Citrus • Earthsherm Jam',record:'0-1',pf:'139.62',note:'JSN, Olave and Montgomery all cooked. The Katz Brothers simply cooked more.',lore:'Big Citrus owns enough aliases to constitute a small media market but still receives only one loss in the standings. Cruel system.'},
{id:'skatt',team:"I'm a Skatt Man",owners:'John Sacripanti',aliases:'Yon • Yonjuries • The Count',record:'0-1',pf:'130.72',note:'Ja’Marr Chase and Jaylen Waddle combined for 4.4 points. There are international treaties governing less hostile acts.',lore:'Deebo scored 20.6 and Denzel Boston 15.9 on the bench. The Count has requested that Week 1 be stricken from the historical record.'},
{id:'ceedeep',team:'CeeDeep Shaheed',owners:'Matt McGrath',aliases:'Matty McGrath',record:'0-1',pf:'129.81',note:'Josh Allen produced 41.26 and then watched almost everyone around him behave like this was somebody else’s emergency.',lore:'The roster contains CeeDee Lamb and Rashid Shaheed, meaning Matty has at least fulfilled the legally nonbinding promise contained in the team name.'},
{id:'danir',team:'DarkHorse Danir',owners:'Danny Demshulum',aliases:'Danir',record:'0-1',pf:'121.14',note:'Lost by 60.46 while Brock Purdy and Kyle Monangai combined for 52 points on the bench. Please direct questions to counsel.',lore:'Gibbs scored 40.5 and Breece Hall 26. This was not enough to overcome Bo Nix, Harrison Mevis and the discovery of Monangai after the fact.'},
{id:'shake-baker',team:"Shake 'N Baker",owners:'Seth Waldenberg',aliases:'Norm • Nails • Woody • Bobby Shmurda • Bobby • The Berg Man',record:'0-1',pf:'105.54',note:'Bijan scored 32.4. The rest of the active roster responded with a coordinated labor slowdown.',lore:'Kyle Pitts scored -1 and Houston D/ST -3.5. Bobby Shmurda has denied that either unit was acting under direct orders from The Berg Man.'},
]
