import {leagueSnapshot} from './league-data';
const franchiseFiles = [
  {
    id: 'all-ugly', team: 'The All Ugly Team', owners: 'Cody + Ferret', aliases: 'Co-managers', record: "0-3", pf: "383.34", pa: "471.69", week1: "L 102.26–167.22 vs Pollard Greens",
    stars: ['Amon-Ra St. Brown — 65.9', 'DeVonta Smith — 40.5', 'Christian Watson — 51.8'], moves: ['Added Demond Claiborne — $0'], coverage: [['all-ugly-process', 'All Ugly Lost With 152.86. The Spreadsheet Has Been Notified.']],
    note: "The Process has now reached 0–3. Week 3 was not another noble scheduling loss; Pollard Greens put up 167.22 and All Ugly answered with 102.26. The dossier has been forced to retire the phrase “good-enough scoring week.”", lore: "All Ugly is now the league’s only 0–3 team. The underlying case can still be litigated, but the standings have stopped accepting exhibits.",
    people: [
      { name: 'Cody', title: 'Director of Process', aliases: 'Cody', bio: 'Cody oversees research, roster construction and the identification of advanced metrics that become urgently important after losses. He believes every fantasy result deserves a complete evidentiary record, particularly when the standings have failed to capture the underlying quality of his work. The Week 1 discovery of Expected Wins is considered his most important contribution to institutional governance.' },
      { name: 'Ferret', title: 'Executive Vice President of Football Restraint', aliases: 'Ferret', bio: 'Ferret serves as co-manager, internal opposition party and the final remaining obstacle between Cody and several theoretically compelling transactions. His precise authority is undocumented, although league observers believe he provides roster judgment, emotional ballast and someone for Cody to ask whether a five-player trade is actually insane. He has declined to describe this as adult supervision.' },
    ],
    posture: "Process under formal review; standings no longer taking testimony.", tendencies: ['Advanced metrics after losses', 'Shared authorship of decisions', 'High evidentiary standards'], incidents: ["Week 1 — Scored 152.86 and lost.", "Week 2 — Scored 128.22 and lost again.", "Week 3 — Lost 167.22–102.26 and became the league’s only 0–3 team."], receipt: "383.34 points. Zero wins. The Expected Wins department has retained outside counsel.",
    mythology: ['The Process — evidence is especially valuable immediately after a loss.', 'Cody + Ferret — two managers, one shared burden of proof.'],
  },
  {
    id: 'hopkins-opus', team: 'Mr Hopkins Opus', owners: 'Kash', aliases: 'Kash • Kush', record: "2-1", pf: "417.84", pa: "348.48", week1: "L 102.84–120.64 vs Lloyd of the Rings",
    stars: ['Kenneth Walker III — 74.6', 'Jonathan Taylor — 56.6', 'Sam LaPorta — 27.0'], moves: ['Added George Holani — $0', 'Added Chris Boswell'], coverage: [['hopkins-opus-statement', 'Kash Posts 181.60. League Braces for Difficult Period of Being Reminded About It.'], ['danir-bench-crime', 'Danir Left 52.0 Points Sitting on the Bench']],
    note: "The first loss finally arrived. Hopkins scored 102.84 in the undefeated-team summit and Lloyd calmly took the game 120.64–102.84.", lore: "Kash still owns a 2–1 record and one of the league’s strongest scoring profiles. The undefeated filing has simply been moved from active evidence to archives.",
    people: [{ name: 'Kash', title: 'Founder and Principal Announcer', aliases: 'Kash • Kush', bio: 'Kash founded the Opus on the belief that a fantasy score is not merely recorded but announced. His management style combines aggressive confidence with a sophisticated document-retention program that ensures favorable results remain available for unrelated future arguments. The Week 1 total of 181.60 is expected to appear in official correspondence through at least 2029.' }],
    posture: "Still dangerous; no longer permitted to say undefeated.", tendencies: ['Publishes favorable results broadly', 'Maintains premium confidence reserves', 'Backups also make the point'], incidents: ["Week 1 — Posted the league-high 181.60.", "Week 2 — Won by 26.70 despite a -0.2 from Jaxson Dart.", "Week 3 — Lost the 2–0 showdown to Lloyd, 120.64–102.84."], receipt: "417.84 points. 2–1. Undefeated stationery discontinued.",
    mythology: ['The Week 1 Filing — 181.60 is now admissible in unrelated arguments until further notice.', 'Kash / Kush — nomenclature varies; confidence does not.'],
  },
  {
    id: 'lloyd-rings', team: 'Lloyd of the Rings', owners: 'Jordan Katz + Brandon Katz', aliases: 'The Katz Brothers', record: "3-0", pf: "430.50", pa: "370.68", week1: "W 120.64–102.84 vs Mr Hopkins Opus",
    stars: ['Derrick Henry — 60.0', 'Dalton Kincaid — 44.5', 'Dak Prescott — 44.76'], moves: ['Added David Njoku — $0', 'Won Caleb Douglas — $20'], coverage: [],
    note: "The Katz family office won the only matchup between unbeaten teams and is now alone at 3–0.", lore: "Lloyd did not need a spectacular total. It needed 120.64, a Hopkins stumble, and the institutional discipline to leave Week 3 as the league’s last perfect team.",
    people: [
      { name: 'Jordan Katz', title: 'Chairman of the Family Office', aliases: 'Jordan', bio: 'Jordan directs the franchise’s long-term strategy and is believed to control at least one of the passwords. His investment philosophy favors established assets, durable production and Derrick Henry continuing to disregard the normal aging process. He maintains that Lloyd is a fantasy team rather than a family business, despite all available organizational evidence.' },
      { name: 'Brandon Katz', title: 'President of Football Operations', aliases: 'Brandon', bio: 'Brandon manages the practical affairs of the Katz enterprise, including lineup administration, personnel review and explaining why the player named Lloyd is not central to Lloyd of the Rings. His working relationship with Jordan is described as collaborative, familial and protected from meaningful external scrutiny. All disagreements are handled privately and later attributed to ESPN.' },
    ],
    posture: "Sole undefeated franchise; family office accepting congratulations.", tendencies: ['Prefers durable assets', 'Private dispute resolution', 'Limited reliance on Lloyd'], incidents: ["Week 1 — Henry and Flowers combined for 73.7.", "Week 2 — Improved to 2–0 with 143.56.", "Week 3 — Beat Hopkins 120.64–102.84 to become the league’s only 3–0 team."], receipt: "430.50 points. 3–0. Family office now controls the undefeated market.",
    mythology: ['The Katz Brothers — a family office with a fantasy roster attached.', 'Lloyd Compliance — the team is not required to receive meaningful points from a Lloyd, apparently.'],
  },
  {
    id: 'royrek', team: 'Royrek Tishmeshulum', owners: 'Max Levene', aliases: 'Bonanz • Bonez', record: "1-2", pf: "381.45", pa: "408.02", week1: "L 113.84–121.76 vs CeeDeep Shaheeded Rivalry",
    stars: ['Davante Adams — 47.6', 'Lamar Jackson — 44.86', 'Justin Jefferson — 41.7'], moves: ['Added Falcons D/ST', 'Dropped Lions D/ST'], coverage: [['all-ugly-process', 'All Ugly Lost With 152.86. The Spreadsheet Has Been Notified.']],
    note: "Royrek got close enough to make the fourth quarter annoying and lost 121.76–113.84 to CeeDeep.", lore: "The stars kept the game viable, but Week 3 converted a 1–1 team into a 1–2 team without providing a scandal large enough to distract from it.",
    people: [{ name: 'Max Levene', title: 'Publicly Listed Owner', aliases: 'Bonanz • Bonez', bio: 'Max is the publicly listed owner of Royrek. The franchise’s annual draft, however, is widely believed to be conducted by Bartone, whose title has ranged from advisor to person visibly making every selection. Max has rejected suggestions that this arrangement compromises team sovereignty, noting that Bartone leaves shortly after the draft and retains only complete influence over the roster.' }],
    associates: [{ name: 'Bartone', title: 'Unregistered Draft Consultant', note: 'No formal ownership stake. No listed franchise position. Widely believed to draft Royrek every year. Exact jurisdiction remains disputed.' }],
    posture: "Star power intact; record now asking for supporting cast.", tendencies: ['Delegates draft-day sovereignty', 'Wins high-scoring disputes', 'Maintains spelling flexibility'], incidents: ["Annual — Bartone reportedly conducts the draft.", "Week 1 — Defeated All Ugly 160.91–152.86.", "Week 3 — Fell 121.76–113.84 to CeeDeep and dropped to 1–2."], receipt: "381.45 points. 1–2. Draft authority still under review.",
    mythology: ['The Bartone Question — league folklore maintains that Bartone drafts this team every year.', 'Bonanz / Bonez — spelling remains less important than attribution.'],
  },
  {
    id: 'kraft', team: 'For the Love of the Kraft', owners: 'Derek Tishman', aliases: 'Tony Tish • Tish', record: "1-2", pf: "360.62", pa: "352.59", week1: "L 116.98–146.57 vs I'm a Skatt man",
    stars: ['D\'Andre Swift — 51.7', 'Joe Burrow — 32.94', 'Jeremiyah Love — 22.5'], moves: ['Won Antonio Williams — $2', 'Dropped Rachaad White'], coverage: [],
    note: "The injury-ravaged Week 3 setup ended exactly as advertised: Kraft scored 116.98 and Skatt finally escaped the winless column with 146.57.", lore: "Quiet competence is now 1–2. The franchise remains respectable in points against, which is useful information if the league ever begins awarding victories for administrative neatness.",
    people: [{ name: 'Derek Tishman', title: 'Chairman of Quiet Competence', aliases: 'Tony Tish • Tish', bio: 'Known interchangeably as Derek, Tony Tish and Tish, he governs through a doctrine of quiet competence that makes him difficult to cover and therefore suspicious. The organization rarely issues statements, manufactures crises or explains why everyone calls Derek “Tony.” Investigators have classified this stability as provisional.' }],
    posture: "Quietly operational; quietly 1–2.", tendencies: ['Avoids unnecessary statements', 'Permits Swift to handle messaging', 'Unexplained alias governance'], incidents: ["Week 1 — Opened 1–0 behind 38.2 from Swift.", "Week 2 — Lost 100.48–95.48 in the league’s lowest-scoring game.", "Week 3 — Lost 146.57–116.98 to give Skatt its first win."], receipt: "360.62 points. 1–2. Quiet competence awaiting louder results.",
    mythology: ['Tony Tish — one of several names available when Derek is being discussed in absentia.', 'Week 1 — quiet competence, pending further evidence.'],
  },
  {
    id: 'route-22', team: 'The Route 22 Clubhouse', owners: 'Danny Choe + Max Gersten', aliases: 'Che • Gerstone', record: "2-1", pf: "424.73", pa: "382.74", week1: "W 137.90–113.44 vs Kupp Kupp Doubs",
    stars: ['James Cook III — 39.2', 'Matthew Stafford — 33.68', 'Tetairoa McMillan — 27.6'], moves: ['Added Emmett Johnson', 'Multiple trade proposals submitted'], coverage: [['route-22-phones', 'Route 22 Won Despite Stafford’s 3.3, Then Immediately Tried to Trade With Everyone']],
    note: "Route 22 ended Kupp’s undefeated run 137.90–113.44 and improved to 2–1. The phones have, regrettably for everyone else, acquired evidence.", lore: "After losing by 0.56 in Week 2, the Clubhouse responded with a 24.46-point win over a 2–0 opponent. Transaction volume will almost certainly be interpreted internally as causation.",
    people: [
      { name: 'Danny Choe', title: 'Director of External Relations', aliases: 'Choe • Che', bio: 'Choe is responsible for maintaining open communication with every franchise, frequently before those franchises have expressed any desire to communicate. His outreach philosophy holds that no player is truly unavailable until the same proposal has been declined in several slightly different configurations. He has also acknowledged a limited advisory role in unrelated institutional controversies without clarifying who requested the advice.' },
      { name: 'Max Gersten', title: 'Chief Transaction Architect', aliases: 'Gerstone', bio: 'Gerstone converts the Clubhouse’s general interest in other people’s players into formal proposals, counterproposals and documents requiring additional scrolling. He specializes in structures where every individual component appears reasonable until the recipient notices there are seven of them. League officials have found no evidence that he has allowed the roster to remain unchanged voluntarily.' },
    ],
    posture: "2–1 and newly empowered to send even more trade proposals.", tendencies: ['Multi-part proposals', 'Persistent external outreach', 'Low tolerance for roster stability'], incidents: ["Week 1 — Won despite 3.3 from Stafford.", "Week 2 — Lost by 0.56 despite Stafford’s 30.38.", "Week 3 — Beat previously undefeated Kupp Kupp Doubs 137.90–113.44."], receipt: "424.73 points. 2–1. The phones have been granted additional funding.",
    mythology: ['The Phones — persistent trade activity is less a strategy than an operating system.', 'The Clubhouse — two managers and apparently no closing bell.'],
  },
  {
    id: 'kupp-doubs', team: 'Kupp Kupp Doubs', owners: 'Roy', aliases: 'Roy Bird', record: "2-1", pf: "357.08", pa: "364.60", week1: "L 113.44–137.90 vs The Route 22 Clubhouse",
    stars: ['Christian McCaffrey — 40.4', 'Jalen Coker — 55.4', 'Isaiah Likely — 36.1'], moves: ['Won 49ers D/ST — $2', 'Won Devaughn Vele — $12'], coverage: [],
    note: "The record finally encountered gravity. Kupp scored 113.44, lost to Route 22, and fell from inexplicable 2–0 to merely difficult-to-explain 2–1.", lore: "The first two weeks proved that ugly wins count. Week 3 supplied the companion lesson: ugly losses also count.",
    people: [{ name: 'Roy Bird', title: 'Keeper of the Strategic Reserve', aliases: 'Roy • Roy Bird', bio: 'Roy operates one of the league’s more traditional franchises: recognizable players, a compliant team name and enough unused bench production to survive an unexpected audit. His decision to preserve Jalen Coker’s 37.8 points during a Week 1 victory has been described internally as strategic inventory management.' }],
    posture: "Still 2–1; undefeated counsel has withdrawn.", tendencies: ['Preserves emergency bench points', 'Maintains naming compliance', 'Avoids unnecessary panic'], incidents: ["Week 1 — Won with Coker’s 37.8 on the bench.", "Week 2 — Won 100.48–95.48.", "Week 3 — Lost 137.90–113.44 to Route 22."], receipt: "357.08 points. 2–1. The record has settled out of court.",
    mythology: ['Roy Bird — the name used by the institution.', 'The Coker Reserve — 37.8 points preserved on the bench during a victory.'],
  },
  {
    id: 'pollard-greens', team: 'Pollard Greens', owners: 'Marc Sherman', aliases: 'Sherm • Sherm the Worm • Big Citrus • Earthsherm Jam', record: "2-1", pf: "456.91", pa: "408.77", week1: "W 167.22–102.26 vs The All Ugly Team",
    stars: ['Jaxon Smith-Njigba — 80.7', 'Chris Olave — 52.8', 'David Montgomery — 33.9'], moves: ['Won Kaleb Johnson — $3', 'Added Justice Hill'], coverage: [],
    note: "Pollard Greens posted 167.22, the second-highest total of Week 3, and turned All Ugly’s process discussion into a fire drill.", lore: "Sherm is 2–1 and leads the league in points scored through three weeks. At some point the alias portfolio may need to include “offensive coordinator.”",
    people: [{ name: 'Marc Sherman', title: 'Commissioner of Names and Municipal Culture', aliases: 'Sherm • Sherm the Worm • Big Citrus • Earthsherm Jam', bio: 'Sherm has accumulated more aliases than several franchises have playoff appearances. Big Citrus, Sherm the Worm and Earthsherm Jam are believed to describe the same individual, although the league has never completed the necessary paperwork. He remains the publication’s default correspondent for inexplicable New York lifestyle developments despite having neither requested nor accepted the position.' }],
    posture: "2–1, league-high 456.91 PF, citrus market bullish.", tendencies: ['Expands the alias portfolio', 'Produces respectable losing totals', 'Receives unsolicited culture assignments'], incidents: ["Week 1 — Scored 139.62 and lost.", "Week 2 — JSN scored 48.5 in a 150.07-point win.", "Week 3 — Dropped 167.22 on All Ugly and moved to 2–1."], receipt: "456.91 points, most in the league. Big Citrus is producing concentrate.",
    mythology: ['The Alias Portfolio — Sherm has accumulated naming rights across multiple eras.', 'Big Citrus — no explanatory note has improved this.'],
  },
  {
    id: 'skatt', team: "I'm a Skatt Man", owners: 'John Sacripanti', aliases: 'Yon • Yonjuries • The Count', record: "1-2", pf: "418.00", pa: "410.21", week1: "W 146.57–116.98 vs For the Love of the Kraft",
    stars: ['Ja\'Marr Chase — 31.7', 'Trey McBride — 42.6', 'Jalen Hurts — 46.08'], moves: ['Won Buccaneers D/ST — $2', 'Dropped Jaguars D/ST'], coverage: [],
    note: "The Count has counted one. Skatt scored 146.57 against Kraft and finally converted solid production into a win.", lore: "At 418 points through three weeks, Skatt’s 1–2 record looks less like collapse than delayed paperwork. Week 3 finally processed the form.",
    people: [{ name: 'John Sacripanti', title: 'Director of Medical Upside', aliases: 'Yon • Yonjuries • The Count', bio: 'Yon approaches roster construction with a pronounced preference for players whose medical information remains developing. This has produced the enduring title “Yonjuries,” which the franchise considers unfair but statistically difficult to challenge. The Count emerges under unspecified circumstances and should not be invoked recreationally.' }],
    posture: "Winless designation revoked; annoyance remains justified.", tendencies: ['Drafts through injury uncertainty', 'Maintains alternate-count identity', 'Finds healthy production on the bench'], incidents: ["Historical — Earned the Yonjuries designation through repeated practice.", "Week 2 — Scored 140.21 and lost anyway.", "Week 3 — Beat Kraft 146.57–116.98 for the first win."], receipt: "418.00 points. One win. The Count has begun.",
    mythology: ['Yonjuries — an alias with enough historical weight to remain on file.', 'The Count — invoked as circumstances require.'],
  },
  {
    id: 'ceedeep', team: 'CeeDeep Shaheed', owners: 'Matt McGrath', aliases: 'Matty McGrath', record: "2-1", pf: "412.79", pa: "388.37", week1: "W 121.76–113.84 vs Royrek Tishmeshulam",
    stars: ['Josh Allen — 86.48', 'CeeDee Lamb — 52.8', 'George Kittle — 23.7'], moves: ['Added Hunter Henry'], coverage: [],
    note: "CeeDeep survived Royrek 121.76–113.84 and moved to 2–1. The concentrated-star model remains solvent.", lore: "Week 2 was the Allen-and-Lamb hostile takeover. Week 3 required less theater and produced the same thing the standings care about: another win.",
    people: [{ name: 'Matt McGrath', title: 'Chief Naming Compliance Officer', aliases: 'Matty McGrath', bio: 'Matty McGrath entered the league with a functioning team name, Josh Allen and no meaningful alias infrastructure. The organization considers this restraint a competitive advantage. After Allen’s five-touchdown Thursday performance, CeeDeep briefly suspended normal operations and asked the remaining players not to complicate anything.' }],
    posture: "2–1; concentrated star power remains fully funded.", tendencies: ['Maintains literal team-name assets', 'Relies on Josh Allen escalation', 'Operates without alias department'], incidents: ["Week 1 — Received 41.26 from Allen and lost.", "Week 2 — Allen and Lamb combined for 83.52.", "Week 3 — Beat Royrek 121.76–113.84 to move to 2–1."], receipt: "412.79 points. 2–1. Naming compliance and winning percentage both improved.",
    mythology: ['Naming Compliance — CeeDee and Shaheed remain on premises.', 'Matty McGrath — currently operating without an alias department.'],
  },
  {
    id: 'danir', team: 'DarkHorse Danir', owners: 'Danny Demshulum', aliases: 'Danir', record: "1-2", pf: "433.25", pa: "510.60", week1: "W 185.48–167.78 vs Shake 'N Baker",
    stars: ['Jahmyr Gibbs — 64.4', 'Breece Hall — 40.8', 'Brock Purdy — 52.38'], moves: ['Added Dontayvion Wicks', 'Added Malik Washington'], coverage: [['danir-bench-crime', 'Danir Left 52.0 Points Sitting on the Bench'], ['hopkins-opus-statement', 'Kash Posts 181.60. League Braces for Difficult Period of Being Reminded About It.']],
    note: "Danir finally got the correction game: 185.48 points, the Week 3 high, and a first win over Shake ’N Baker.", lore: "The dark horse stopped being theoretical for one week. A roster that spent two weeks explaining losses simply outscored everyone in Week 3.",
    people: [{ name: 'Danny Demshulum', title: 'Custodian of Undeployed Production', aliases: 'Danir', bio: 'Danir’s philosophy holds that the most dangerous points are the ones an opponent cannot see because they remain securely stored on the bench. Brock Purdy and Kyle Monangai demonstrated this doctrine with 52 unused Week 1 points. The franchise continues to describe itself as a dark horse, although the horse’s lineup status should be confirmed Sunday morning.' }],
    posture: "Reform program produced the week’s highest score.", tendencies: ['Preserves bench production', 'Discovers optimal lineups retrospectively', 'Maintains dark-horse classification'], incidents: ["Week 1 — Left 52.0 points from Purdy and Monangai on the bench.", "Week 2 — Corrected both decisions and still lost by 34.59.", "Week 3 — Scored a league-high 185.48 and beat Shake ’N Baker."], receipt: "185.48 in Week 3. First win secured. Bench-crime file temporarily sealed.",
    mythology: ['The Week 1 Bench File — Purdy + Monangai, 52.0 points, untouched.', 'DarkHorse — a name currently being tested under adverse conditions.'],
  },
  {
    id: 'shake-baker', team: "Shake 'N Baker", owners: 'Seth Waldenberg', aliases: 'Norm • Nails • Woody • Bobby Shmurda • Bobby • The Berg Man', record: "1-2", pf: "412.81", pa: "472.57", week1: "L 167.78–185.48 vs DarkHorse Danir",
    stars: ['Bijan Robinson — 44.1', 'Tre Tucker — 34.6', 'Travis Kelce — 28.1'], moves: [], coverage: [],
    note: "Shake scored 167.78 — a total that wins most weeks — and ran directly into Danir’s 185.48.", lore: "Week 2’s 0.56 miracle has been followed by the opposite kind of variance: excellent scoring, no procedural error required, still a loss.",
    people: [{ name: 'Seth Waldenberg', title: 'Administrator of the Alias System', aliases: 'Norm • Nails • Woody • Bobby Shmurda • Bobby • The Berg Man', bio: 'Seth operates through an unusually deep alias structure that includes Norm, Nails, Woody, Bobby, Bobby Shmurda and The Berg Man. It is unclear which identity submits the lineup or whether they have equal voting rights. Bijan Robinson is currently the only employee confirmed to have reported for work in Week 1.' }],
    posture: "Scored 167.78 and lost; alias department preparing appeal.", tendencies: ['Maintains six active aliases', 'Delegates production to Bijan', 'Issues denials through alternate identities'], incidents: ["Week 1 — Bijan was present; several colleagues were technically also present.", "Week 2 — Won by 0.56 with Tre Tucker’s 28.9 on the bench.", "Week 3 — Scored 167.78 and lost to the week’s highest-scoring team."], receipt: "167.78 points. Loss. Variance has requested equal time.",
    mythology: ['The Waldenberg Alias System — Norm, Nails, Woody, Bobby, Bobby Shmurda and The Berg Man remain equally valid.', 'Week 1 — Bijan was present. Several colleagues were technically also present.'],
  },
]

const currentNotes={
  "all-ugly": "Skatt won 149.47–132.98, leaving All Ugly at 0–4. The first win is still outstanding; the latest evidence is a 16.49-point loss, not an accounting error.",
  "hopkins-opus": "Hopkins beat Pollard Greens by 2.54 and moves to 3–1. First place is restored, with considerably less room for rhetorical expansion than the opening-week blowout.",
  "lloyd-rings": "CeeDeep ended the unbeaten run, 147.07–141.28. Lloyd is 3–1, with Emanuel Wilson’s 30.6-point FLEX performance a good decision inside a losing result.",
  "ceedeep": "CeeDeep beat the previously unbeaten Katz family office by 5.79. At 3–1, the rivalry now has a fresh receipt and a place among the four teams sharing the best record.",
  "kupp-doubs": "Kupp beat Danir 143.62–125.42 and moves to 3–1. The standings recognize the win even if the opposing bench has requested a separate hearing.",
  "danir": "Danir is 1–3 after losing to Kupp by 18.20. Kyle Monangai’s 35 bench points exceeded the margin, and the FLEX decision has become a particularly difficult exhibit.",
  "route-22": "Route 22 scored 167.94 and lost to Kraft by 0.28. The Clubhouse is 2–2; two of its losses now total 0.84 points, after Week 2’s 0.56-point defeat.",
  "kraft": "Kraft survived 168.22–167.94 in the week’s highest-scoring matchup. At 2–2, the franchise has two wins and a new reason to defend the second decimal place.",
  "skatt": "Skatt beat All Ugly 149.47–132.98 and reaches 2–2. Kyren Williams supplied 39.8 points, more than enough to give the organization a preferable subject of conversation.",
  "pollard-greens": "Pollard Greens leads the league with 610.07 points but sits 2–2 after a 2.54-point loss to Hopkins. Production remains convincing; the schedule remains unpersuaded.",
  "royrek": "Royrek beat Shake ’N Baker 133.88–130.24 and reaches 2–2. A 3.64-point margin counts as a full win, a conversion rate the franchise has no reason to challenge.",
  "shake-baker": "Shake ’N Baker falls to 1–3 after losing to Royrek by 3.64. The Week 2 escape by 0.56 is still on file; it does not provide credit toward this result."
};
export const teams=franchiseFiles.map(t=>{
 const ops=leagueSnapshot.teams[t.id];
 if(!ops)return t;
 const last=ops.season.weekly.at(-1);
 const note=currentNotes[t.id]||t.note;
 return {...t,record:ops.record,pf:ops.pointsFor.toFixed(2),pa:ops.pointsAgainst.toFixed(2),note,lore:note,week1:`${last.result} ${last.score.toFixed(2)}–${last.opponentScore.toFixed(2)} vs ${last.opponent}`,posture:`${ops.record} • ${ops.seed} in the table • Week ${leagueSnapshot.week} complete`,receipt:`${ops.pointsFor.toFixed(2)} points. ${ops.record}. Through Week ${leagueSnapshot.week}.`,stars:[...ops.roster].sort((a,b)=>b.seasonPoints-a.seasonPoints).slice(0,3).map(p=>`${p.name} — ${p.seasonPoints.toFixed(1)}`)};
});
