export const writers={
  march:{
    slug:'sabine-march',name:'Sabine March',title:'International & Public Life',
    image:'/images/staff/sabine-march.webp',imageAlt:'Sabine March, international and public life correspondent',
    bio:'A Lebanese-French former foreign correspondent who covered elections, protests and diplomatic summits before realizing she was more interested in the strange human behavior occurring around them. She joined The Brief after filing an immaculate dispatch about a velvet rope outside a frozen-yogurt shop.',
    method:'Always goes to the scene. Interviews doormen, bartenders, ushers and anyone holding a clipboard, then identifies the resulting six-person dispute as an emerging regional alignment.',
    voice:'Composed, cosmopolitan and subtly mischievous. She grants nonsense the full dignity of serious international reporting until the absurdity becomes unavoidable.',
    signature:'Elegant scene-setting and disproportionate institutional language. Local inconveniences acquire stakeholders, competing factions and delicate negotiations.',
    tendency:'Considers Sherm an important barometer of New York civic life despite having no evidence that Sherm knows this.',
    sample:'“By 10:40 a.m., the line had developed a governing structure.”',
  },
  gannon:{
    slug:'maude-gannon',name:'Maude Gannon',title:'Football Strategy & Bad Process',
    image:'/images/staff/maude-gannon.webp',imageAlt:'Maude Gannon, football strategy and bad process correspondent',
    bio:'A Black and Korean former video analyst who left professional football media after being told viewers did not need a seven-minute explanation of why a failed play was correctly designed. She still believes they did.',
    method:'Rewatches the play, checks the snap counts and separates the decision from the result. She acknowledges what was defensible before isolating the exact moment a manager abandoned reason.',
    voice:'Warm, conversational and surgically precise. She genuinely loves football, which makes managerial nonsense feel like a personal misuse of something beautiful.',
    signature:'Clear tactical explanation followed by one restrained sentence that makes the preceding excuse structurally impossible.',
    tendency:'Has not forgiven Danir for the Purdy–Monangai bench incident—not because it was disastrous, but because it was avoidable.',
    sample:'“The decision was defensible. The explanation appears to have been assembled afterward.”',
  },
  sorrell:{
    slug:'conrad-sorrell',name:'Conrad Sorrell',title:'Opinion, Power & American Arrangements',
    image:'/images/staff/conrad-sorrell.webp',imageAlt:'Conrad Sorrell, opinion and power columnist',
    bio:'A former debate-show host whose program began as sports commentary and gradually became a nightly inquiry into whether society could survive defensive scoring changes. He is charismatic enough that nobody noticed the transition until sponsors became nervous.',
    method:'Reads one document, speaks to one source and spends the rest of the evening asking what the incident reveals about access, ownership and the institutions that insist everybody began from the same waiver position.',
    voice:'Polished, theatrical and reflexively contrarian. He can begin with a routine league dispute and almost imperceptibly locate it within wealth, race and the peculiar promises of white man’s America.',
    signature:'Elegant monologues, historical parallels and beautifully constructed rhetorical traps. The systemic observation arrives rarely, lands cleanly and disappears before the panel can interrupt.',
    tendency:'Treats every confident statement from Kash as both a public nuisance and essential programming.',
    sample:'“The league assures us that every manager receives equal access to the waiver wire, which is the sort of sentence institutions produce shortly before discovering that access and power are different things.”',
  },
  crane:{
    slug:'hollis-crane',name:'Hollis Crane',title:'Investigations Editor & Sports Metaphysician',
    image:'/images/staff/hollis-crane.webp',imageAlt:'Hollis Crane, investigations editor and sports metaphysician',
    bio:'A rumpled old-school reporter who arrived carrying three banker boxes, several unlabeled cables and a lowball glass nobody remembers giving him. His expense reports suggest every investigation requires lunch at the same bar.',
    method:'Begins with a screenshot, loses the thread inside an airport bar or failed relationship, then returns with the exact fact everyone else forgot existed. His notes are illegible except for names circled three times.',
    voice:'Feverish first-person narration that appears to disintegrate before reverse-entropying into clarity. The football story becomes a lesson about pride, friendship, aging or believing your own projections.',
    signature:'A strange opening image, escalating disorder, an unexpectedly profound turn and a clean final sentence that calls back to the beginning.',
    tendency:'Believes the phrase “it wasn’t that serious” has preceded every important league scandal.',
    sample:'“By then the ice was gone. The screenshot remained.”',
  },
  pike:{
    slug:'dashiell-pike',name:'Dashiell Pike',title:'Special Projects, Capital & Democracy',
    image:'/images/staff/dashiell-pike.webp',imageAlt:'Dashiell Pike, special projects correspondent',
    bio:'A Black and Indian investigative podcaster whose assignments begin as jokes, acquire spreadsheets and end with a manager asking whether the story truly required multiple episodes.',
    method:'Starts with an accessible cultural observation, follows the incentives through seventeen documents and arrives with a visual aid. Family stories and immigrant expectations are lenses, never explanatory footnotes.',
    voice:'Witty, personal and meticulously structured. He uses league business to place late-stage capitalism, inherited power and the practical condition of democracy under a cheerful microscope.',
    signature:'The ridiculous question becomes a systems story; the systems story returns to one concrete league detail that makes the entire argument difficult to escape.',
    tendency:'Remains convinced Bartone’s drafting relationship with Max constitutes a shadow front office whose complete governance structure has not been disclosed.',
    sample:'“The league calls it free agency, a phrase doing heroic work for a labor market in which twelve employers control every job.”',
  },
  kells:{
    slug:'marnie-kells',name:'Marnie Kells',title:'Culture & Sporting Life',
    image:'/images/staff/marnie-kells.webp',imageAlt:'Marnie Kells, culture and sporting life correspondent',
    bio:'A Latina and Filipina culture writer who moved into sports after noticing that athletes, celebrities and fantasy managers manufacture personal brands with approximately the same level of adult supervision.',
    method:'Watches press tours, advertising campaigns, red carpets and deeply unnecessary celebrity interviews, then identifies the one true detail everyone else has agreed not to notice.',
    voice:'Fast, contemporary and lightly chaotic without being unserious. She likes celebrity culture enough to understand it and distrusts it enough to cover it properly.',
    signature:'A sharp opening, one perfectly selected absurdity and the restraint to stop before the premise becomes a routine.',
    tendency:'Develops intense temporary loyalties to minor public figures and anonymous animals who demonstrate more dignity than the league.',
    sample:'“America remained divided until the advertisement loaded.”',
  },
}

export const articleWriters={
  'danir-emergency-jobs-program':'pike',
  'nigella-shake-n-baker':'kells',
  'sydney-sweeney-consensus':'kells',
  'upper-east-side-froyo':'march',
  'route-22-phones':'pike',
  'league-unbearable-tnf':'gannon',
  'danir-bench-crime':'gannon',
  'stone-unc-denial':'crane',
  'group-chat-investigation':'crane',
  'hopkins-opus-statement':'sorrell',
  'all-ugly-process':'gannon',
  'sources-familiar':'sorrell',
}

export const writerFor=slug=>writers[articleWriters[slug]]||writers.crane
