create table if not exists public.brief_editorial_runs (
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 status text not null default 'queued',
 packet jsonb not null default '{}'::jsonb,
 pitches jsonb,
 decision jsonb,
 draft jsonb,
 error text,
 attempts integer not null default 0
);
alter table public.brief_editorial_runs enable row level security;
create index if not exists brief_editorial_runs_status_idx on public.brief_editorial_runs(status,created_at);
