create table if not exists public.brief_editorial_memory (
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 writer text not null,
 premise_key text not null,
 thesis text not null,
 subject_entities text[] not null default '{}',
 evidence jsonb not null default '{}'::jsonb,
 outcome text not null default 'published',
 source_post_id bigint,
 unique(writer,premise_key)
);
alter table public.brief_editorial_memory enable row level security;
create index if not exists brief_editorial_memory_created_idx on public.brief_editorial_memory(created_at desc);
create index if not exists brief_editorial_memory_writer_idx on public.brief_editorial_memory(writer,created_at desc);