-- Multi-tenant product foundation for The Brief.
-- Global newsroom canon remains in brief_correspondents / brief_canonical_assets.
create extension if not exists pgcrypto;

create table if not exists public.brief_tenants (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  publication_name text not null default 'The Brief',
  status text not null default 'active' check (status in ('active','paused','archived')),
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.brief_leagues (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.brief_tenants(id) on delete cascade,
  provider text not null check (provider in ('espn','yahoo','sleeper','manual')),
  provider_league_key text,
  name text not null,
  season integer not null,
  sport text not null default 'nfl',
  status text not null default 'active' check (status in ('onboarding','active','paused','archived')),
  settings jsonb not null default '{}'::jsonb,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider, provider_league_key, season)
);

create table if not exists public.brief_provider_connections (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.brief_tenants(id) on delete cascade,
  provider text not null,
  provider_user_id text,
  access_token_enc text,
  refresh_token_enc text,
  token_expires_at timestamptz,
  scopes text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending','active','expired','revoked','error')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.brief_league_members (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references public.brief_leagues(id) on delete cascade,
  provider_manager_key text,
  display_name text not null,
  real_name text,
  email text,
  role text not null default 'member' check (role in ('owner','editor','member')),
  profile jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(league_id, provider_manager_key)
);

create table if not exists public.brief_league_teams (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references public.brief_leagues(id) on delete cascade,
  member_id uuid references public.brief_league_members(id) on delete set null,
  provider_team_key text not null,
  name text not null,
  abbreviation text,
  logo_url text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(league_id, provider_team_key)
);

create table if not exists public.brief_league_memory (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.brief_leagues(id) on delete cascade,
  subject_type text not null check (subject_type in ('league','manager','team','rivalry','joke','event','preference')),
  subject_key text,
  memory_key text not null,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'active' check (status in ('active','retired','disputed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.brief_publication_articles (
  id uuid primary key default gen_random_uuid(),
  scope text not null check (scope in ('global','league','network')),
  league_id uuid references public.brief_leagues(id) on delete cascade,
  writer_slug text references public.brief_correspondents(slug) on delete set null,
  slug text not null,
  section text,
  title text not null,
  dek text,
  body jsonb not null default '[]'::jsonb,
  hero jsonb not null default '{}'::jsonb,
  status text not null default 'draft' check (status in ('draft','review','published','archived')),
  homepage_rank integer,
  published_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((scope='league' and league_id is not null) or (scope in ('global','network'))),
  unique(scope, league_id, slug)
);

create index if not exists brief_leagues_tenant_idx on public.brief_leagues(tenant_id);
create index if not exists brief_provider_connections_tenant_idx on public.brief_provider_connections(tenant_id);
create index if not exists brief_league_members_league_idx on public.brief_league_members(league_id);
create index if not exists brief_league_teams_league_idx on public.brief_league_teams(league_id);
create index if not exists brief_league_memory_league_idx on public.brief_league_memory(league_id, status);
create index if not exists brief_publication_articles_scope_idx on public.brief_publication_articles(scope, league_id, status, published_at desc);

alter table public.brief_tenants enable row level security;
alter table public.brief_leagues enable row level security;
alter table public.brief_provider_connections enable row level security;
alter table public.brief_league_members enable row level security;
alter table public.brief_league_teams enable row level security;
alter table public.brief_league_memory enable row level security;
alter table public.brief_publication_articles enable row level security;

insert into public.brief_tenants (slug,name,publication_name,settings)
values ('league-of-ordinary-gentlemen','League of Ordinary Gentlemen','The Brief of Ordinary Gentleman','{"canonical":true}'::jsonb)
on conflict (slug) do nothing;
